// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DueSent struct {
	SentID    *int             `json:"sentId"`
	MediaURI  *string          `json:"mediaUri"`
	SentWords []*TriedSentWord `json:"sentWords"`
}

type IncorrectSeenSent struct {
	SentID         *int             `json:"sentId"`
	IndexInArticle *int             `json:"indexInArticle"`
	SentWords      []*TriedSentWord `json:"sentWords"`
}

type LoginToken struct {
	Success bool    `json:"success"`
	Token   *string `json:"token"`
}

type Message struct {
	Success bool    `json:"success"`
	Message *string `json:"message"`
}

type SeenSent struct {
	SentID         *int   `json:"sentId"`
	IndexInArticle *int   `json:"indexInArticle"`
	TryText        string `json:"tryText"`
}

type TriedSentWord struct {
	Length         int     `json:"length"`
	IsCloze        bool    `json:"isCloze"`
	Wordform       string  `json:"wordform"`
	IndexInSent    int     `json:"indexInSent"`
	LastInputText  string  `json:"lastInputText"`
	LastInputScore float64 `json:"lastInputScore"`
}

type TrySentInput struct {
	SentID        int    `json:"sentId"`
	UserInputJSON string `json:"userInputJson"`
}

type TrySentScore struct {
	Success *bool    `json:"success"`
	Score   *float64 `json:"score"`
}

type UnseenSent struct {
	SentID         *int              `json:"sentId"`
	IndexInArticle *int              `json:"indexInArticle"`
	MediaURI       *string           `json:"mediaUri"`
	SentWords      []*UnseenSentWord `json:"sentWords"`
}

type UnseenSentWord struct {
	Length      int    `json:"length"`
	IsCloze     bool   `json:"isCloze"`
	Wordform    string `json:"wordform"`
	IndexInSent int    `json:"indexInSent"`
}

type UserArticle struct {
	ArticleID          *int    `json:"articleId"`
	ArticleTitle       string  `json:"articleTitle"`
	ArticleSentCount   int     `json:"articleSentCount"`
	ArticleDescription *string `json:"articleDescription"`
	UserFinishedIndex  *int    `json:"userFinishedIndex"`
}

type UserCredentials struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Email    *string `json:"email"`
}

type UserIdentity struct {
	Username string `json:"username"`
	LoggedIn bool   `json:"loggedIn"`
}
