export const displaySeenSents = [
  {
    sentId: 15,
    indexInArticle: 1,
    tryText:
      "Dxt xr x5 mxl melxxx mixx sxrxvxoxd i Malmö oxh xäxmxsxe xrxnxsxax txlx Ukraina , Mxdxkx , ex lxtxn xoxsx bx mxd xåxrx txsxn xnxåxaxe .",
  },
  {
    sentId: 16,
    indexInArticle: 2,
    tryText:
      "På andra sxdxn gränsen pågår ett krig , inte ett sådant som utspelar sig i spalter och debattprogram , utan ett sådant som dödar människor och utplånar städer .",
  },
  {
    sentId: 17,
    indexInArticle: 3,
    tryText:
      "Mot bakgrund av detta ter sig samtalet i den svenska offentligheten som vi har vant oss vid det som bisarrt .",
  },
];

export const displayUnseenSents = [
  {
    sentId: 18,
    indexInArticle: 4,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_04.mp3",
    sentWords: [
      {
        length: 1,
        isCloze: true,
        wordform: "I",
        indexInSent: 1,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "åratal",
        indexInSent: 2,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 3,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ett",
        indexInSent: 4,
      },
      {
        length: 11,
        isCloze: true,
        wordform: "oförsonligt",
        indexInSent: 5,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "kulturkrig",
        indexInSent: 6,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "rasat",
        indexInSent: 7,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 8,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "med",
        indexInSent: 9,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "offer",
        indexInSent: 10,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "till",
        indexInSent: 11,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "både",
        indexInSent: 12,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "höger",
        indexInSent: 13,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 14,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "vänster",
        indexInSent: 15,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 16,
      },
    ],
  },
  {
    sentId: 19,
    indexInArticle: 5,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_05.mp3",
    sentWords: [
      {
        length: 4,
        isCloze: true,
        wordform: "båda",
        indexInSent: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "sidor",
        indexInSent: 2,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "lika",
        indexInSent: 3,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "övertygade",
        indexInSent: 4,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "om",
        indexInSent: 5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "sin",
        indexInSent: 6,
      },
      {
        length: 14,
        isCloze: true,
        wordform: "förträfflighet",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 8,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "om",
        indexInSent: 9,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "att",
        indexInSent: 10,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "just",
        indexInSent: 11,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "deras",
        indexInSent: 12,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "världsbild",
        indexInSent: 13,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 14,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "korrekt",
        indexInSent: 15,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 16,
      },
    ],
  },
  {
    sentId: 20,
    indexInArticle: 6,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_06.mp3",
    sentWords: [
      {
        length: 3,
        isCloze: true,
        wordform: "Det",
        indexInSent: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 2,
      },
      {
        length: 11,
        isCloze: true,
        wordform: "framställts",
        indexInSent: 3,
      },
      {
        length: 1,
        isCloze: true,
        wordform: " ",
        indexInSent: 4,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 5,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 6,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "kamp",
        indexInSent: 7,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "mellan",
        indexInSent: 8,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "mörker",
        indexInSent: 9,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 10,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "ljus",
        indexInSent: 11,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 12,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 13,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "människor",
        indexInSent: 14,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 15,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 16,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "ofta",
        indexInSent: 17,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "på",
        indexInSent: 18,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "tämligen",
        indexInSent: 19,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "dunkla",
        indexInSent: 20,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "grunder",
        indexInSent: 21,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 22,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "dubbats",
        indexInSent: 23,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "till",
        indexInSent: 24,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "goda",
        indexInSent: 25,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "eller",
        indexInSent: 26,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "dömts",
        indexInSent: 27,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 28,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "onda",
        indexInSent: 29,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 30,
      },
    ],
  },
  {
    sentId: 21,
    indexInArticle: 7,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_07.mp3",
    sentWords: [
      {
        length: 7,
        isCloze: true,
        wordform: "Hjältar",
        indexInSent: 1,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 2,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "martyrer",
        indexInSent: 3,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 4,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "profeter",
        indexInSent: 5,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "–",
        indexInSent: 6,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 7,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Greta",
        indexInSent: 8,
      },
      {
        length: 8,
        isCloze: false,
        wordform: "Thunberg",
        indexInSent: 9,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 10,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Cissi",
        indexInSent: 11,
      },
      {
        length: 6,
        isCloze: false,
        wordform: "Wallin",
        indexInSent: 12,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 13,
      },
      {
        length: 8,
        isCloze: false,
        wordform: "Katerina",
        indexInSent: 14,
      },
      {
        length: 7,
        isCloze: false,
        wordform: "Janouch",
        indexInSent: 15,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 16,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Hanif",
        indexInSent: 17,
      },
      {
        length: 4,
        isCloze: false,
        wordform: "Bali",
        indexInSent: 18,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 19,
      },
      {
        length: 6,
        isCloze: false,
        wordform: "Joakim",
        indexInSent: 20,
      },
      {
        length: 7,
        isCloze: false,
        wordform: "Lamotte",
        indexInSent: 21,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 22,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "allt",
        indexInSent: 23,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "efter",
        indexInSent: 24,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "tycke",
        indexInSent: 25,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 26,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "smak",
        indexInSent: 27,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "–",
        indexInSent: 28,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 29,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "kommit",
        indexInSent: 30,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 31,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "gått",
        indexInSent: 32,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 33,
      },
    ],
  },
  {
    sentId: 22,
    indexInArticle: 8,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_08.mp3",
    sentWords: [
      {
        length: 7,
        isCloze: true,
        wordform: "Varenda",
        indexInSent: 1,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "människa",
        indexInSent: 2,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 3,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "någon",
        indexInSent: 4,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "gång",
        indexInSent: 5,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "publicerat",
        indexInSent: 6,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 7,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "åsikt",
        indexInSent: 8,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 9,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "nogsamt",
        indexInSent: 10,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "sorterats",
        indexInSent: 11,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "in",
        indexInSent: 12,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 13,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "oavsett",
        indexInSent: 14,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "om",
        indexInSent: 15,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "man",
        indexInSent: 16,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "vill",
        indexInSent: 17,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "vara",
        indexInSent: 18,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 19,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "del",
        indexInSent: 20,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "av",
        indexInSent: 21,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "detta",
        indexInSent: 22,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "fiktiva",
        indexInSent: 23,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "krig",
        indexInSent: 24,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "eller",
        indexInSent: 25,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 26,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 27,
      },
    ],
  },
  {
    sentId: 23,
    indexInArticle: 9,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_09.mp3",
    sentWords: [
      {
        length: 12,
        isCloze: true,
        wordform: "Diskussioner",
        indexInSent: 1,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "om",
        indexInSent: 2,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "vilka",
        indexInSent: 3,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ord",
        indexInSent: 4,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 5,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 6,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "tillåtna",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 8,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "otillåtna",
        indexInSent: 9,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 10,
      },
      {
        length: 15,
        isCloze: true,
        wordform: "uppförandekoder",
        indexInSent: 11,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "för",
        indexInSent: 12,
      },
      {
        length: 17,
        isCloze: true,
        wordform: "standup-branschen",
        indexInSent: 13,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 14,
      },
    ],
  },
  {
    sentId: 24,
    indexInArticle: 10,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_10.mp3",
    sentWords: [
      {
        length: 3,
        isCloze: true,
        wordform: "vem",
        indexInSent: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 2,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 3,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ond",
        indexInSent: 4,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "respektive",
        indexInSent: 5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "god",
        indexInSent: 6,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 7,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "vilka",
        indexInSent: 8,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "pronomen",
        indexInSent: 9,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 10,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 11,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "lämpliga",
        indexInSent: 12,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ter",
        indexInSent: 13,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "sig",
        indexInSent: 14,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "nu",
        indexInSent: 15,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 16,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "väldigt",
        indexInSent: 17,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "obsoleta",
        indexInSent: 18,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 19,
      },
    ],
  },
  {
    sentId: 25,
    indexInArticle: 11,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_11.mp3",
    sentWords: [
      {
        length: 7,
        isCloze: true,
        wordform: "Världen",
        indexInSent: 1,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 2,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 3,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "bara",
        indexInSent: 4,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 5,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "berättelse",
        indexInSent: 6,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "Den",
        indexInSent: 8,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 9,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 10,
      },
    ],
  },
  {
    sentId: 26,
    indexInArticle: 12,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_12.mp3",
    sentWords: [
      {
        length: 9,
        isCloze: true,
        wordform: "Människan",
        indexInSent: 1,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 2,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 3,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "blott",
        indexInSent: 4,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 5,
      },
      {
        length: 12,
        isCloze: true,
        wordform: "konstruktion",
        indexInSent: 6,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "Hon",
        indexInSent: 8,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 9,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 10,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "kropp",
        indexInSent: 11,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 12,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "känner",
        indexInSent: 13,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 14,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "lider",
        indexInSent: 15,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 16,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "dör",
        indexInSent: 17,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 18,
      },
    ],
  },
  {
    sentId: 27,
    indexInArticle: 13,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_13.mp3",
    sentWords: [
      {
        length: 4,
        isCloze: true,
        wordform: "Krig",
        indexInSent: 1,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "förs",
        indexInSent: 2,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 3,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "bara",
        indexInSent: 4,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "på",
        indexInSent: 5,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "Twitter",
        indexInSent: 6,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 7,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "utan",
        indexInSent: 8,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "på",
        indexInSent: 9,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "gator",
        indexInSent: 10,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 11,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "torg",
        indexInSent: 12,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 13,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "vapen",
        indexInSent: 14,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 15,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 16,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "bara",
        indexInSent: 17,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ord",
        indexInSent: 18,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 19,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "utan",
        indexInSent: 20,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "gevär",
        indexInSent: 21,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 22,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "bomber",
        indexInSent: 23,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 24,
      },
    ],
  },
  {
    sentId: 28,
    indexInArticle: 14,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_14.mp3",
    sentWords: [
      {
        length: 5,
        isCloze: true,
        wordform: "Trots",
        indexInSent: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "dessa",
        indexInSent: 2,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "uppenbara",
        indexInSent: 3,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "påpekanden",
        indexInSent: 4,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ser",
        indexInSent: 5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "jag",
        indexInSent: 6,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "hur",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "det",
        indexInSent: 8,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "pågående",
        indexInSent: 9,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "kriget",
        indexInSent: 10,
      },
      {
        length: 1,
        isCloze: true,
        wordform: "i",
        indexInSent: 11,
      },
      {
        length: 7,
        isCloze: false,
        wordform: "Ukraina",
        indexInSent: 12,
      },
      {
        length: 15,
        isCloze: true,
        wordform: "fiktionaliseras",
        indexInSent: 13,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 14,
      },
    ],
  },
  {
    sentId: 29,
    indexInArticle: 15,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_15.mp3",
    sentWords: [
      {
        length: 2,
        isCloze: true,
        wordform: "Vi",
        indexInSent: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "har",
        indexInSent: 2,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "två",
        indexInSent: 3,
      },
      {
        length: 13,
        isCloze: true,
        wordform: "huvudpersoner",
        indexInSent: 4,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "den",
        indexInSent: 6,
      },
      {
        length: 12,
        isCloze: true,
        wordform: "hjältemodige",
        indexInSent: 7,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "president",
        indexInSent: 8,
      },
      {
        length: 9,
        isCloze: false,
        wordform: "Zelenskyj",
        indexInSent: 9,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 10,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "den",
        indexInSent: 11,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "galne",
        indexInSent: 12,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "diktatorn",
        indexInSent: 13,
      },
      {
        length: 8,
        isCloze: false,
        wordform: "Vladimir",
        indexInSent: 14,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Putin",
        indexInSent: 15,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 16,
      },
    ],
  },
  {
    sentId: 30,
    indexInArticle: 16,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_16.mp3",
    sentWords: [
      {
        length: 7,
        isCloze: true,
        wordform: "Sociala",
        indexInSent: 1,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "medier",
        indexInSent: 2,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "fylls",
        indexInSent: 3,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "av",
        indexInSent: 4,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "hyllningar",
        indexInSent: 5,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "till",
        indexInSent: 6,
      },
      {
        length: 9,
        isCloze: false,
        wordform: "Zelenskyj",
        indexInSent: 7,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 8,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "nidbilder",
        indexInSent: 9,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "av",
        indexInSent: 10,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Putin",
        indexInSent: 11,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 12,
      },
    ],
  },
  {
    sentId: 31,
    indexInArticle: 17,
    mediaUri:
      "https://d1zg52ope8o24c.cloudfront.net/zelenskyj/zelenskyj_17.mp3",
    sentWords: [
      {
        length: 9,
        isCloze: true,
        wordform: "reportage",
        indexInSent: 1,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "om",
        indexInSent: 2,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "den",
        indexInSent: 3,
      },
      {
        length: 10,
        isCloze: true,
        wordform: "osannolike",
        indexInSent: 4,
      },
      {
        length: 11,
        isCloze: true,
        wordform: "presidenten",
        indexInSent: 5,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 6,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "från",
        indexInSent: 7,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "komiker",
        indexInSent: 8,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "till",
        indexInSent: 9,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "statschef",
        indexInSent: 10,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "skrivs",
        indexInSent: 11,
      },
      {
        length: 1,
        isCloze: true,
        wordform: "i",
        indexInSent: 12,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "rasande",
        indexInSent: 13,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "fart",
        indexInSent: 14,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 15,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "liksom",
        indexInSent: 16,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "analyser",
        indexInSent: 17,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 18,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "avfärdar",
        indexInSent: 19,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Putin",
        indexInSent: 20,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 21,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 22,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "sjuk",
        indexInSent: 23,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 24,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 25,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 26,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "vansinnig",
        indexInSent: 27,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 28,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 29,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 30,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "galen",
        indexInSent: 31,
      },
      {
        length: 1,
        isCloze: false,
        wordform: "”",
        indexInSent: 32,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 33,
      },
    ],
  },
];

export const examineCorrectSents = [
  {
    sentId: 17,
    indexInArticle: 3,
    tryText:
      "Mot bakgrund av detta ter sig samtalet i den svenska offentligheten som vi har vant oss vid det som bisarrt .",
  },
];

export const examineIncorrectSents = [
  {
    sentId: 15,
    indexInArticle: 1,
    sentWords: [
      {
        length: 3,
        isCloze: true,
        wordform: "Det",
        indexInSent: 1,
        lastInputText: "Dxt",
        lastInputScore: 0.6666667,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "är",
        indexInSent: 2,
        lastInputText: "xr",
        lastInputScore: 0.6666667,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "75",
        indexInSent: 3,
        lastInputText: "x5",
        lastInputScore: 0.5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "mil",
        indexInSent: 4,
        lastInputText: "mxl",
        lastInputScore: 0.6666667,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "mellan",
        indexInSent: 5,
        lastInputText: "melxxx",
        lastInputScore: 0.5,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "mitt",
        indexInSent: 6,
        lastInputText: "mixx",
        lastInputScore: 0.5,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "skrivbord",
        indexInSent: 7,
        lastInputText: "sxrxvxoxd",
        lastInputScore: 0.5555556,
      },
      {
        length: 1,
        isCloze: true,
        wordform: "i",
        indexInSent: 8,
        lastInputText: "i",
        lastInputScore: 1,
      },
      {
        length: 5,
        isCloze: false,
        wordform: "Malmö",
        indexInSent: 9,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 10,
        lastInputText: "oxh",
        lastInputScore: 0.6666667,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "närmaste",
        indexInSent: 11,
        lastInputText: "xäxmxsxe",
        lastInputScore: 0.5555556,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "gränsstad",
        indexInSent: 12,
        lastInputText: "xrxnxsxax",
        lastInputScore: 0.5,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "till",
        indexInSent: 13,
        lastInputText: "txlx",
        lastInputScore: 0.5,
      },
      {
        length: 7,
        isCloze: false,
        wordform: "Ukraina",
        indexInSent: 14,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 15,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "Medyka",
        indexInSent: 16,
        lastInputText: "Mxdxkx",
        lastInputScore: 0.5,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 17,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "en",
        indexInSent: 18,
        lastInputText: "ex",
        lastInputScore: 0.5,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "liten",
        indexInSent: 19,
        lastInputText: "lxtxn",
        lastInputScore: 0.6,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "polsk",
        indexInSent: 20,
        lastInputText: "xoxsx",
        lastInputScore: 0.4,
      },
      {
        length: 2,
        isCloze: true,
        wordform: "by",
        indexInSent: 21,
        lastInputText: "bx",
        lastInputScore: 0.5,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "med",
        indexInSent: 22,
        lastInputText: "mxd",
        lastInputScore: 0.6666667,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "några",
        indexInSent: 23,
        lastInputText: "xåxrx",
        lastInputScore: 0.5,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "tusen",
        indexInSent: 24,
        lastInputText: "txsxn",
        lastInputScore: 0.6,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "invånare",
        indexInSent: 25,
        lastInputText: "xnxåxaxe",
        lastInputScore: 0.5555556,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 26,
        lastInputText: "",
        lastInputScore: 0,
      },
    ],
  },
  {
    sentId: 16,
    indexInArticle: 2,
    sentWords: [
      {
        length: 2,
        isCloze: true,
        wordform: "På",
        indexInSent: 1,
        lastInputText: "På",
        lastInputScore: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "andra",
        indexInSent: 2,
        lastInputText: "andra",
        lastInputScore: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "sidan",
        indexInSent: 3,
        lastInputText: "sxdxn",
        lastInputScore: 0.6,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "gränsen",
        indexInSent: 4,
        lastInputText: "gränsen",
        lastInputScore: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "pågår",
        indexInSent: 5,
        lastInputText: "pågår",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ett",
        indexInSent: 6,
        lastInputText: "ett",
        lastInputScore: 1,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "krig",
        indexInSent: 7,
        lastInputText: "krig",
        lastInputScore: 1,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 8,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "inte",
        indexInSent: 9,
        lastInputText: "inte",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ett",
        indexInSent: 10,
        lastInputText: "ett",
        lastInputScore: 1,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "sådant",
        indexInSent: 11,
        lastInputText: "sådant",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 12,
        lastInputText: "som",
        lastInputScore: 1,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "utspelar",
        indexInSent: 13,
        lastInputText: "utspelar",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "sig",
        indexInSent: 14,
        lastInputText: "sig",
        lastInputScore: 1,
      },
      {
        length: 1,
        isCloze: true,
        wordform: "i",
        indexInSent: 15,
        lastInputText: "i",
        lastInputScore: 1,
      },
      {
        length: 7,
        isCloze: true,
        wordform: "spalter",
        indexInSent: 16,
        lastInputText: "spalter",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 17,
        lastInputText: "och",
        lastInputScore: 1,
      },
      {
        length: 13,
        isCloze: true,
        wordform: "debattprogram",
        indexInSent: 18,
        lastInputText: "debattprogram",
        lastInputScore: 1,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ",",
        indexInSent: 19,
        lastInputText: "",
        lastInputScore: 0,
      },
      {
        length: 4,
        isCloze: true,
        wordform: "utan",
        indexInSent: 20,
        lastInputText: "utan",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "ett",
        indexInSent: 21,
        lastInputText: "ett",
        lastInputScore: 1,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "sådant",
        indexInSent: 22,
        lastInputText: "sådant",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "som",
        indexInSent: 23,
        lastInputText: "som",
        lastInputScore: 1,
      },
      {
        length: 5,
        isCloze: true,
        wordform: "dödar",
        indexInSent: 24,
        lastInputText: "dödar",
        lastInputScore: 1,
      },
      {
        length: 9,
        isCloze: true,
        wordform: "människor",
        indexInSent: 25,
        lastInputText: "människor",
        lastInputScore: 1,
      },
      {
        length: 3,
        isCloze: true,
        wordform: "och",
        indexInSent: 26,
        lastInputText: "och",
        lastInputScore: 1,
      },
      {
        length: 8,
        isCloze: true,
        wordform: "utplånar",
        indexInSent: 27,
        lastInputText: "utplånar",
        lastInputScore: 1,
      },
      {
        length: 6,
        isCloze: true,
        wordform: "städer",
        indexInSent: 28,
        lastInputText: "städer",
        lastInputScore: 1,
      },
      {
        length: 1,
        isCloze: false,
        wordform: ".",
        indexInSent: 29,
        lastInputText: "",
        lastInputScore: 0,
      },
    ],
  },
];
